CHANGES.rst
docs/hooks.rst
transaction/_transaction.py
transaction/tests/test__transaction.py

Per [the discussion on the mailing list](https://groups.google.com/forum/#!topic/python-transaction/oUzj3uIHBgA)
This is the bare implementation of that, only freeing resources when _manager.free() is called. A few notes:
- We could also free the manager instance. This breaks a test in hooks.rst though.
- The free method is not being called in a finally block. In the case of abort() this is probably acceptable because each individual data manager is protected by a try/except. Presumably in the case of a failed commit(), though, we are expecting people to turn around and call abort()? So in practice this should all work out?
- Possible behaviour change: the synchronizers' `afterCompletion` methods are now being called with `_resources` empty (the manager would already have been cleared …

Free DataManagers when a transaction becomes non-current.

---

CHANGES.rst
transaction/_transaction.py
transaction/interfaces.py
transaction/tests/test__transaction.py

For objects such as data managers or their subobjects that
work with multiple transactions, it's convenient to store
transaction-specific data on the transaction itself.  The
transaction knows nothing about the data, but simply holds it
on behalf of the object.
Discussion:
https://groups.google.com/forum/#!topic/python-transaction/oUzj3uIHBgA

New transaction API for storing data on behalf of objects

---

.coveragerc

Coverage 4.1 defaults 'show_missing' to False.
See http://stackoverflow.com/questions/37733194/python-nosetests-with-coverage-no-longer-shows-missing-lines/37746141#37746141

Restore display of missing lines.

---

CHANGES.rst
transaction/interfaces.py
transaction/tests/test__transaction.py

ITransaction had two misplaced 'self' parameters. I removed them. Also, Transaction no longer implements the long-deprecated beforeCommitHook method, so I removed it from the interface. I added new tests to verify the implementation of the interface.

Corrected ITransaction: removed beforeCommitHook and 2 misplaced 'self' parameters

---

CHANGES.rst
docs/api.rst
docs/convenience.rst
transaction/_manager.py
transaction/interfaces.py
transaction/tests/test__manager.py

This implements: https://groups.google.com/forum/#!topic/python-transaction/3eUzBzX2sRU
In addition, this moves the attempts doctest in the docs to a regular tests.  While I like doctests, I don't like to clutter documentation with tests.   The attempts method was bad enough without weird examples muddying the documentation.

Run decorator, a simpler alternative to attempts

---

CHANGES.rst
transaction/_transaction.py
transaction/interfaces.py
transaction/tests/test__transaction.py

This fixes #26 and #27.
- The transaction ``user`` and ``description`` attributes are now  defined to be text (unicode) as opposed
to Python the ``str`` type.
- Added the ``extended_info`` transaction attribute which contains
transaction meta data.  (The ``_extension`` attribute is retained as
an alias for backward compatibility.)
The transaction interface, ``ITransaction``, now requires
``extended_info`` keys to be text (unicode) and values to be
JSON-serializable.

Transaction meta data cleanup

---

CHANGES.rst
transaction/_transaction.py
transaction/tests/test__transaction.py

Fixed: Some legacy applications expect the transaction _extension
attribute to be settable and it wasn't.
Existing ZEO builds will be broken without this fix.

URGENT: _extension needs to be settable

---

CHANGES.rst
docs/convenience.rst
transaction/_manager.py
transaction/_transaction.py
transaction/tests/test__transaction.py

Insist that transaction user and description are text (unicode)
See: https://groups.google.com/forum/#!topic/zodb/U0H1kTh_dY4
There will be much breakage because of this for Python 2.7 applications. I had to fix quite a few ZODB tests, although that may not be a great indicator.

Hate bytes

---

CHANGES.rst
docs/index.rst
transaction/_manager.py
transaction/interfaces.py
transaction/tests/test__manager.py

Added a transaction-manager explicit mode. Explicit mode makes some
kinds of application bugs easier to detect and potentially allows data
managers to manage resources more efficiently.
(This addresses https://github.com/zopefoundation/transaction/issues/35.)

Explicit mode

---

CHANGES.rst
transaction/_compat.py
transaction/_transaction.py
transaction/tests/test__transaction.py

For backward compatibility, relax the requirements that transaction meta data (user or description) be text

---

transaction/_transaction.py
transaction/tests/test__transaction.py

Restores 100% coverage.
`tox -e coverage` was failing with:
```python
Name                          Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------
transaction.py                   14      0      0      0   100%
transaction/_compat.py           13      0      0      0   100%
transaction/_manager.py         134      0     62      0   100%
transaction/_transaction.py     407      0    126      1    99%   139->exit
transaction/interfaces.py         9      0      0      0   100%
transaction/weakset.py           22      0      4      0   100%
-------------------------------------------------------------------------
TOTAL                           599      0    192      1    99%
nose.plugins.cover: ERROR: TOTAL Coverage did …
```

Add test for 'txn.user = None'.

---

docs/hooks.rst

Document that hooks must not raise / propagate exceptions.

---

transaction/_manager.py
transaction/_transaction.py
transaction/interfaces.py
transaction/tests/test__transaction.py

Fixes https://github.com/zopefoundation/transaction/issues/37.
Some discussion is here: https://groups.google.com/d/msg/python-transaction/7-965JdlBy0/OX8BPFDTBgAJ
I'm not sure what the right approach is to add a new method to `ITransaction` but I think it's the right place for this feature. Surely there is a way as everything in the library has an interface, so there must be a way to change them or we can never add features. :-)

expose ITransaction.isRetryableError

---

.travis.yml
CHANGES.rst
setup.py
tox.ini

- drop support for Python 3.4
- add support for Python 3.7
- bump to new major version, as Python 3.4 is still supported by
Debian 8
modified:   .travis.yml
modified:   CHANGES.rst
modified:   setup.py
modified:   tox.ini

Modernize Python versions

---

CHANGES.rst
transaction/_manager.py
transaction/interfaces.py
transaction/tests/test__manager.py

This PR documents `attempts` and  `run` in `transaction.interfaces.ITransactionManager` and implements `run` in terms of `attempts` (which properly uses transaction manager methods for transaction control). This fixes #58

Fix transaction manager run problems #58

---

CHANGES.rst
transaction/_compat.py
transaction/_transaction.py
transaction/interfaces.py
transaction/tests/test__transaction.py

Support abort hooks (symmetrically to commit hooks) #77

---

docs/api.rst
docs/datamanager.rst
docs/resourcemanager.rst
transaction/interfaces.py

Also fix the lexing and highlighting of two doctest blocks.

Publish the docs for the two explicit-mode exceptions added in 2.1.0.

---

CHANGES.rst
docs/hooks.rst
transaction/_transaction.py
transaction/tests/test__transaction.py

Specifically, free the manager and synchronizers, plus a few other dictionaries that could be arbitrary size and some of which could contain arbitrary data.
And `abort()` always invokes `_free()` even in the case of exceptions. `commit()` still doesn't so that the synchronizers are available for the expected abort().
But take care about when and how abort frees its manager: not only does this preserve backwards compatibility, but it lets it be safe to abort a transaction object more than once. A happy side-effect of only freeing the manager there is that synchronizers can access
data they set in `afterCompletion()`.
Previously, this code would raise `ValueError`; it now does nothing on the second call to `abort`:
```python
tx = transaction.get()
tx.abort()
transaction.get()
tx.abort()
``` …

Transaction._free drops more references, and Transaction.abort() is a bit safer

---

docs/hooks.rst

From the documentation I got the wrong impression that the the hooks adder methods would take arguments as in `*args`.
But this is not the case as internally `tuple(args)` is called. This works for strings of length 1 as expected but it is an edge case which should not be stressed in the documentation.

Fix documentation of args parameter

---

.travis.yml

The xenial build of pypy on Travis CI links against OpenSSL 1.0.2, which
causes pip install cryptography to fail with
RuntimeError: You are linking against OpenSSL 1.0.2, which is no longer
supported by the OpenSSL project. To use this version of cryptography
you need to upgrade to a newer version of OpenSSL. For this version only
you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102
to allow OpenSSL 1.0.2.
Note that 'pypy' is not a valid Python version when using dist: bionic
or dist: focal and you have to use 'pypy2' instead.

Use dist: focal on Travis

---

CHANGES.rst
src/transaction/_transaction.py
src/transaction/tests/test__transaction.py

Before commit hooks do not ask for cleaning and are expected to raise the exception.
Refactoring in 5aef8c2a accidentally introduced a return in a `finally:` block.  Because a return in finally block takes priority over raised exception, if one hook failed, remaining hooks were simply not executed, no error was logged, and we proceeded with committing the transaction anyway.

Make before commit hooks raise exceptions again, broken in 2.4.1

---

.github/workflows/tests.yml
.meta.toml
tox.ini

Use `Sphinx < 4` to prevent problems with `repoze.sphinx.autointerface`.

Fix generating documentation.

---

src/transaction/tests/test__manager.py

Testing with Python 3.11 via `tox -e py311` we get two deprecation warnings:
```
...
/private/tmp/transaction/src/transaction/tests/test_weakset.py:140: DeprecationWarning: unittest.makeSuite() is deprecated and will be removed in Python 3.13. Please use unittest.TestLoader.loadTestsFromTestCase() instead.
return unittest.makeSuite(WeakSetTests)
Running tests at level 1
Running zope.testrunner.layer.UnitTests tests:
Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
Running:
/private/tmp/transaction/src/transaction/tests/test__manager.py:711: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
self.setDaemon(True)
...
```
https://github.com/zopefoundation/transaction/actions/runs/5037515550/jobs/9034409507#step:6:25
Let's fix them.
Also Python 3.12 is now …

Fix deprecation warning

---

setup.py

With the drop of Python 2.7 the tests where ported but the test_requires still kept mock.

Drop the test dependency on mock

---

docs/conf.py

See https://github.com/zopefoundation/transaction/actions/runs/10157793918/job/28088564452 for a broken test
and https://github.com/zopefoundation/transaction/actions/runs/10157793918/job/28088564189 for the deprecation warnings.

Fix Sphinx conf to support version 8+.
